version: '3.8'

services:
  db:
    image: postgres
    container_name: socially-postgres
    restart: always
    environment:
      POSTGRES_USER: rudra
      POSTGRES_PASSWORD: rudra
      POSTGRES_DB: socailly_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
